services:
  - type: web
    name: solicitud-informe-tecnico
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
